### ISSUE TITLE
Support for dark/light mode

### ISSUE THREAD

**Issue by GinoongFlores** [GinoongFlores/ginoongflores.github.io#1]

**Comment by ShamsudinBakaev** [comment]
Hi! I was interested in this problem, and I've already begun to solve it

**Comment by GinoongFlores** [comment]
> Hi! I was interested in this problem, and I've already begun to solve it

Hello @ShamsudinBakaev! The issues here are my personal todo's for this portfolio. I was surprise someone would contribute. Yet, Feel free to open a PR for this feature. Your contribution is much appreciated. Thanks!

**Comment by ShamsudinBakaev** [comment]
> > Hi! I was interested in this problem, and I've already begun to solve it
> 
> Hello @ShamsudinBakaev! The issues here are my personal todo's for this portfolio. I was surprise someone would contribute. Yet, Feel free to open a PR for this feature. Your contribution is much appreciated. Thanks!

Problem solved! Thank you for the interesting task!

**Comment by GinoongFlores** [comment]
Closed issue. Feature enhancement achieved through @ShamsudinBakaev contribution on https://github.com/GinoongFlores/ginoongflores.github.io/pull/2
